### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib.nccl'

### ISSUE THREAD

**Issue by molo32** [genforce/idinvert#40]
error when training encoder.
gpu: t4
linux
tensorflow version 1

```
Creating the run dir: results/00014-stylegan-encoder-1gpu-256x256-ffhq
Copying files to the run dir
WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/tfutil.py:34: The name tf.Dimension is deprecated. Please use tf.compat.v1.Dimension instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/tfutil.py:74: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/tfutil.py:128: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Using TensorFlow backend.
dnnlib: Running training.training_loop_encoder.training_loop() on localhost...
WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/tfutil.py:97: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/tfutil.py:109: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/tfutil.py:132: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /content/idinvert/training/training_loop_encoder.py:109: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Constructing networks...
WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/network.py:142: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/network.py:150: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/tfutil.py:76: The name tf.VariableScope is deprecated. Please use tf.compat.v1.VariableScope instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/network.py:151: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/network.py:182: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /content/idinvert/dnnlib/tflib/tfutil.py:200: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From <string>:373: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "train_encoder.py", line 69, in <module>
    main()
  File "train_encoder.py", line 65, in main
    dnnlib.submit_run(**kwargs)
  File "/content/idinvert/dnnlib/submission/submit.py", line 290, in submit_run
    run_wrapper(submit_config)
  File "/content/idinvert/dnnlib/submission/submit.py", line 242, in run_wrapper
    util.call_func_by_name(func_name=submit_config.run_func_name, submit_config=submit_config, **submit_config.run_func_kwargs)
  File "/content/idinvert/dnnlib/util.py", line 257, in call_func_by_name
    return func_obj(*args, **kwargs)
  File "/content/idinvert/training/training_loop_encoder.py", line 125, in training_loop
    num_layers=num_layers, is_training=True, num_gpus=submit_config.num_gpus, **Encoder_args)
  File "/content/idinvert/dnnlib/tflib/network.py", line 88, in __init__
    module, self._build_func_name = util.get_module_from_obj_name(func_name)
  File "/content/idinvert/dnnlib/util.py", line 219, in get_module_from_obj_name
    importlib.import_module(module_name) # may raise ImportError
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/idinvert/training/networks_encoder.py", line 11, in <module>
    from tensorflow.contrib.nccl.ops import gen_nccl_ops
ModuleNotFoundError: No module named 'tensorflow.contrib.nccl'
```

**Comment by zhujiapeng** [comment]
check https://github.com/genforce/idinvert/issues/21#issuecomment-696655320 and https://github.com/genforce/idinvert/issues/11#issuecomment-671303849.
